name: test
on: [push, pull_request]
jobs:
  upload-test-coverage:
    name: test-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          # use own token to upload coverage reports
          token: ${{ secrets.CODECOV_TOKEN }}
